opensrp-path/build.gradle

Increments app version to 1.2.2 with version code 8.

Version 1.2.2

---

opensrp-path/build.gradle

Changed package name

---

opensrp-path/src/main/assets/special_vaccines.json
opensrp-path/src/main/assets/vaccines.json
opensrp-path/src/main/java/org/smartregister/path/activity/ChildDetailTabbedActivity.java
opensrp-path/src/main/java/org/smartregister/path/activity/ChildImmunizationActivity.java
opensrp-path/src/main/java/org/smartregister/path/application/VaccinatorApplication.java
opensrp-path/src/main/java/org/smartregister/path/tabfragments/ChildUnderFiveFragment.java
opensrp-path/src/main/res/menu/menu_child_detail_settings.xml
opensrp-path/src/main/res/values/strings.xml
opensrp-path/src/test/java/org/smartregister/path/activity/ChildDetailTabbedActivityUnitTest.java
opensrp-path/src/test/java/shared/VaccinatorApplicationTestVersion.java

https://github.com/OpenSRP/opensrp-client/issues/426
Relies on https://github.com/OpenSRP/opensrp-client-immunization/pull/7

Check bcg scar

---

opensrp-path/src/main/res/layout/nav_header_base.xml
opensrp-path/src/main/res/values/dimens.xml

Update white background

---

opensrp-path/src/main/java/org/smartregister/path/activity/HIA2ReportsActivity.java
opensrp-path/src/main/java/org/smartregister/path/fragment/SendMonthlyDraftDialogFragment.java
opensrp-path/src/main/java/util/MoveToMyCatchmentUtils.java
opensrp-path/src/main/res/layout/dialog_fragment_send_monthly.xml
opensrp-path/src/main/res/values/strings.xml

Cleanup hia2 submission dialog

---

README.md

Add screenshots about the app, brief app walkthrough for end-user & explanations of widgets, colors & abbreviations used.

Document OpenMRS Path app

---

opensrp-path/build.gradle
opensrp-path/src/main/java/org/smartregister/path/activity/ChildImmunizationActivity.java
opensrp-path/src/main/java/org/smartregister/path/fragment/PathJsonFormFragment.java
opensrp-path/src/main/java/util/PathConstants.java
opensrp-path/src/test/java/org/smartregister/path/activity/ChildDetailTabbedActivityUnitTest.java

Signed-off-by: Martin Ndegwa <ndegwamartin@gmail.com>

Fix bug in weight modal

---

opensrp-path/src/main/java/org/smartregister/path/activity/ChildDetailTabbedActivity.java
opensrp-path/src/main/java/org/smartregister/path/activity/ChildImmunizationActivity.java
opensrp-path/src/main/java/org/smartregister/path/provider/ChildSmartClientsProvider.java
opensrp-path/src/main/java/org/smartregister/path/sync/PathClientProcessor.java
opensrp-path/src/main/java/org/smartregister/path/wrapper/VaccineViewRecordUpdateWrapper.java
opensrp-path/src/main/java/util/JsonFormUtils.java
opensrp-path/src/main/java/util/Utils.java

Fix overdue count due to mr/measles vaccine being given

---

opensrp-path/src/main/java/org/smartregister/path/activity/ChildSmartRegisterActivity.java
opensrp-path/src/main/java/org/smartregister/path/fragment/BaseSmartRegisterFragment.java

Fix search by qr code

---

opensrp-path/src/main/java/org/smartregister/path/activity/PathJsonFormActivity.java

Fix for M/MR lost adjustment error

---

opensrp-path/src/main/assets/ec_client_fields.json
opensrp-path/src/main/java/org/smartregister/path/fragment/AdvancedSearchFragment.java

Fixed advanced search mother/guardian phonenumber in my catchment area

---

opensrp-path/build.gradle
opensrp-path/src/main/java/org/smartregister/path/sync/PathUpdateActionsTask.java
opensrp-path/src/main/res/values/strings.xml

Solves the "Sync Complete" message that was being shown even if sync was not completed. Now the message shown is "Sync failed" when sync does not complete
Parent issue is in opensrp-server repository

Investigate syncing issues

---

opensrp-path/src/main/java/org/smartregister/path/activity/ChildSmartRegisterActivity.java
opensrp-path/src/main/java/util/JsonFormUtils.java

This fixes one of the issues in #117 
On saving the birth registration form, the device would be unresponsive.

EK | Fix unresponsive app when saving birth registration form

---

opensrp-path/build.gradle
opensrp-path/src/main/java/org/smartregister/path/fragment/AdvancedSearchFragment.java
opensrp-path/src/main/java/util/Utils.java
opensrp-path/src/main/res/values/strings.xml
opensrp-path/src/test/java/util/UtilsTest.java

Signed-off-by: Martin Ndegwa <ndegwamartin@gmail.com>

Advanced Search allows user to select earlier End date than Start date for dob range

---

opensrp-path/src/main/java/org/smartregister/path/tabfragments/ChildRegistrationDataFragment.java
opensrp-path/src/main/java/org/smartregister/path/tabfragments/ChildUnderFiveFragment.java
opensrp-path/src/main/res/layout/child_registration_data_fragment.xml
opensrp-path/src/main/res/layout/fragment_child_registration_data.xml

How to reproduce:
* Open the ZEIR app
* Click on a child
* Click on the child basic details card/rectangle
The app takes time to open the Health Details page or shows a black screen

Slow and unresponsive app - Opening a child's health details

---

opensrp-path/src/main/java/org/smartregister/path/tabfragments/ChildRegistrationDataFragment.java

Fix Child's residential area not showing up correctly for some patients

---

opensrp-path/build.gradle

Updated core to 1.1.0
Removed enketo functionality in version 1.1.0

Updated core to 1.1.0

---

opensrp-path/src/main/java/org/smartregister/path/activity/PathJsonFormActivity.java

For more information https://github.com/OpenSRP/opensrp-client-path/issues/151

Add check for valid integer string

---

opensrp-path/build.gradle
opensrp-path/src/main/java/org/smartregister/path/activity/ChildDetailTabbedActivity.java
opensrp-path/src/main/java/org/smartregister/path/tabfragments/ChildUnderFiveFragment.java

Fix for updating weight layout

---

opensrp-path/src/main/java/org/smartregister/path/activity/LoginActivity.java

For more https://github.com/OpenSRP/opensrp-client-path/issues/144

Fix getViewTreeObserver on null object - Check for null

---

opensrp-path/src/main/java/org/smartregister/path/fragment/AdvancedSearchFragment.java

For more on the issue https://github.com/OpenSRP/opensrp-client-path/issues/104

Fix Advanced Search date range to not allow future dates

---

opensrp-path/build.gradle

Updated core and immunization dependencies

---

opensrp-path/src/main/java/org/smartregister/path/provider/ChildSmartClientsProvider.java
opensrp-path/src/main/res/values/strings.xml

Disabled showing vaccine card for an out of area child

---

opensrp-path/build.gradle
opensrp-path/src/main/assets/json.form/stock_issued_form.json
opensrp-path/src/main/assets/json.form/stock_received_form.json

Integer data types for stock vials

---

README.md

Signed-off-by: Andre Lesa <andre@andrelesa.com>
Issue: https://github.com/OpenSRP/opensrp-client-path/issues/167

Americanize the word "immunization".

---

.travis.yml
opensrp-path/src/test/java/shared/BaseUnitTest.java
opensrp-path/src/test/java/shared/customshadows/ShadowRealmDatabase.java

Fix broken travis build

---

opensrp-path/build.gradle

Updated core to 1.1.3

---

opensrp-path/build.gradle

Update native form version to fix spinner fields not displaying

Update native form version

---

opensrp-path/build.gradle
opensrp-path/src/main/java/org/smartregister/path/activity/BaseRegisterActivity.java

Use [Kujaku](https://github.com/onaio/kujaku) Bundle Extra Keys for the broadcast intent.
Related to https://github.com/onaio/kujaku/pull/36

Kujaku - expose mapservice constants

---

opensrp-path/src/main/java/org/smartregister/path/service/HIA2Service.java

Can capture all qualifying children.

Fix CH2055 CH2060 HIA2 indicators

---

opensrp-path/src/main/java/org/smartregister/path/service/HIA2Service.java

Similar fix as https://github.com/OpenSRP/opensrp-client-path/pull/222.
Accept:
CH2075 rst.type = 'deworming' instead of rst.type = 'Deworming' 
CH2080 rst.type = 'itn' instead of rst.type = 'ITN'

Fix CH2075 CH2080 HIA2 indicators

---

opensrp-path/src/main/java/org/smartregister/path/activity/BaseActivity.java
opensrp-path/src/main/java/org/smartregister/path/activity/ChildDetailTabbedActivity.java

Fixes the following navigation options on the navigation view:
- Add new child
- Record out of catchment vaccination

Fix navigation drawer broken in Child Details Activity

---

opensrp-path/src/main/java/org/smartregister/path/activity/ChildDetailTabbedActivity.java
opensrp-path/src/main/java/org/smartregister/path/domain/CumulativePatient.java
opensrp-path/src/main/java/org/smartregister/path/fragment/AdvancedSearchFragment.java
opensrp-path/src/main/java/org/smartregister/path/repository/CumulativePatientRepository.java
opensrp-path/src/main/java/org/smartregister/path/service/intent/CoverageDropoutIntentService.java
opensrp-path/src/main/java/util/JsonFormUtils.java
opensrp-path/src/main/java/util/MoveToMyCatchmentUtils.java
opensrp-path/src/main/java/util/PathConstants.java

Fixed move to catchment bug in 
https://github.com/OpenSRP/opensrp-client-path/issues/173
https://github.com/OpenSRP/opensrp-client-path/issues/174
Fixed issue 
https://github.com/OpenSRP/opensrp-client-path/issues/227

Move to catchment fix for coverage and dropout reports

---

opensrp-path/build.gradle

Updated core to 1.1.7

---

opensrp-path/build.gradle
opensrp-path/src/main/java/org/smartregister/path/activity/BaseActivity.java
opensrp-path/src/main/java/org/smartregister/path/activity/BaseRegisterActivity.java
opensrp-path/src/main/java/org/smartregister/path/activity/ChildDetailTabbedActivity.java
opensrp-path/src/main/java/org/smartregister/path/activity/ChildSmartRegisterActivity.java
opensrp-path/src/main/java/org/smartregister/path/map/DisplayToastInterface.java
opensrp-path/src/main/java/org/smartregister/path/map/MapHelper.java
opensrp-path/src/main/java/org/smartregister/path/map/OfflineMapDownloadUpdatesReceiver.java
opensrp-path/src/main/java/org/smartregister/path/map/OfflineMapUpdatesReceiver.java
opensrp-path/src/main/java/org/smartregister/path/map/OfflineSwitchUtils.java
opensrp-path/src/main/java/org/smartregister/path/view/StatusSnackbar.java
opensrp-path/src/main/res/values/colors.xml
opensrp-path/src/main/res/values/strings.xml

The latest version is 
- 0.2.4-56-2
- Update native form with bug fix for disappearing spinners
- Update constants usage
- Remove deprecated parcelables for the MapActivity
- Update Kujaku Config **NB: Later after this has been added by @jasonrogena PR https://github.com/onaio/kujaku/pull/47  & any related issues fixed**
- When Offline mode is disabled, show a dilalog box asking whether to delete previously downloaded maps
- Implement Info window double click
- Implement Offline switch in BaseActivity

Update Kujaku library to latest version

---

opensrp-path/build.gradle
opensrp-path/src/main/java/org/smartregister/path/activity/BaseActivity.java
opensrp-path/src/main/java/org/smartregister/path/activity/ChildDetailTabbedActivity.java
opensrp-path/src/main/java/org/smartregister/path/activity/ChildImmunizationActivity.java
opensrp-path/src/main/java/org/smartregister/path/activity/ChildSmartRegisterActivity.java
opensrp-path/src/main/java/org/smartregister/path/activity/LoginActivity.java
opensrp-path/src/main/java/org/smartregister/path/adapter/ServiceLocationsAdapter.java
opensrp-path/src/main/java/org/smartregister/path/domain/jsonmapping/FormLocation.java
opensrp-path/src/main/java/org/smartregister/path/fragment/AdvancedSearchFragment.java
opensrp-path/src/main/java/org/smartregister/path/fragment/BaseSmartRegisterFragment.java
opensrp-path/src/main/java/org/smartregister/path/fragment/SetCsoDialogFragment.java
opensrp-path/src/main/java/org/smartregister/path/helper/LocationHelper.java
opensrp-path/src/main/java/org/smartregister/path/interactors/PathJsonFormInteractor.java
opensrp-path/src/main/java/org/smartregister/path/listener/BaseListener.java
opensrp-path/src/main/java/org/smartregister/path/repository/DailyTalliesRepository.java
opensrp-path/src/main/java/org/smartregister/path/service/intent/SyncService.java
opensrp-path/src/main/java/org/smartregister/path/sync/PathClientProcessorForJava.java
opensrp-path/src/main/java/org/smartregister/path/tabfragments/ChildRegistrationDataFragment.java
opensrp-path/src/main/java/org/smartregister/path/toolbar/LocationSwitcherToolbar.java
opensrp-path/src/main/java/org/smartregister/path/view/LocationActionView.java
opensrp-path/src/main/java/org/smartregister/path/view/LocationPickerView.java
opensrp-path/src/main/java/org/smartregister/path/widgets/PathDatePickerFactory.java
opensrp-path/src/main/java/org/smartregister/path/widgets/PathEditTextFactory.java
opensrp-path/src/main/java/util/JsonFormUtils.java
opensrp-path/src/main/java/util/LocationUtils.java
opensrp-path/src/main/java/util/Utils.java

Depends on https://github.com/OpenSRP/opensrp-client-core/pull/57

Login clean up

---

opensrp-path/build.gradle
opensrp-path/src/main/assets/vaccines.json
opensrp-path/src/main/java/org/smartregister/path/activity/ChildDetailTabbedActivity.java
opensrp-path/src/main/java/org/smartregister/path/activity/ChildImmunizationActivity.java
opensrp-path/src/main/java/org/smartregister/path/application/VaccinatorApplication.java
opensrp-path/src/main/java/org/smartregister/path/tabfragments/ChildUnderFiveFragment.java
opensrp-path/src/main/java/util/AsyncTaskUtils.java
opensrp-path/src/main/java/util/JsonFormUtils.java

PR for [Issue 268](https://github.com/OpenSRP/opensrp-client-path/issues/268)

Convert vaccines json assets to java for faster processing

---

opensrp-path/build.gradle

Related to https://github.com/OpenSRP/opensrp-client-core/pull/59

Updated core to 1.2.3-Snapshot

---

opensrp-path/src/main/java/org/smartregister/path/fragment/AdvancedSearchFragment.java
opensrp-path/src/main/java/util/MoveToMyCatchmentUtils.java

Fixed advanced search bugs

---

opensrp-path/build.gradle
opensrp-path/src/main/java/org/smartregister/path/provider/ChildSmartClientsProvider.java
opensrp-path/src/main/java/util/PathConstants.java

Updated logic for fully immunized status

---

opensrp-path/build.gradle

updated core to 1.2.6-SNAPSHOT, immunization to 1.2.5-SNAPSHOT

---

opensrp-path/src/main/java/org/smartregister/path/repository/CohortPatientRepository.java
opensrp-path/src/main/java/org/smartregister/path/repository/CumulativePatientRepository.java
opensrp-path/src/main/java/org/smartregister/path/service/intent/CoverageDropoutIntentService.java

Fixed undo redo bug

---

opensrp-path/build.gradle
opensrp-path/src/main/AndroidManifest.xml

Update ZEIR to enable support for multiple OpenSRP side by side installs with the take photo feature
Depends on this PR https://github.com/OpenSRP/opensrp-client-native-form/pull/17

Update ZEIR to enable support for multiple OpenSRP side by side installs

---

opensrp-path/build.gradle
opensrp-path/src/test/java/shared/customshadows/ImmunizationRowCardShadow.java

Depends on https://github.com/OpenSRP/opensrp-client-immunization/pull/37

Updated to snapshots, immunization to 1.2.6-SNAPSHOT

---

opensrp-path/build.gradle
opensrp-path/src/main/java/org/smartregister/path/fragment/SendMonthlyDraftDialogFragment.java
opensrp-path/src/main/java/org/smartregister/path/fragment/SetCsoDialogFragment.java
opensrp-path/src/main/java/org/smartregister/path/fragment/StatusEditDialogFragment.java

Popups on start causes app crash

---

opensrp-path/build.gradle
opensrp-path/src/main/res/values/strings.xml

Added custom server response message

---

opensrp-path/build.gradle

Related to https://github.com/OpenSRP/opensrp-client-path/issues/313 and https://github.com/OpenSRP/opensrp-client-path/issues/314

Fix for vit a ifc 2 bugs

---

opensrp-path/build.gradle
opensrp-path/src/main/java/org/smartregister/path/activity/ChildImmunizationActivity.java

1. Wait for all vaccine wrappers to be updated before getting due vaccine wrappers
2. Update immunization library to version with notification on vaccine wrapper-group update completion
Depends on https://github.com/OpenSRP/opensrp-client-immunization/pull/42
See #350

Fix wrong vaccination dialog being openned

---

opensrp-path/build.gradle

Updated Immunization version to 1.2.13-SNAPSHOT
